### ISSUE TITLE
Q1 Recruiting

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/recruiting#1]
### Overview
- Establish Ubiquity’s presence in Seoul. 
- Recruit key strategic talent. 
### Deliverables
- [x] #2
- [x] #3
- [x] #4
- [ ] Possible office set up.

**Comment by 0x4007** [comment]
@diamondnegroni posting this here for task tracking, and so that you can regularly post updates under each task and receive credit for it.

**Comment by diamondnegroni** [comment]
Update as of Feb 5 
*Rocket Punch (local recruiting platform)
-96 interested, 2 applied (all korean)


*Linkedin 
-45 views, 19 applicants (all non-korean)
-one in-person interview

**Comment by diamondnegroni** [comment]
Updated (Feb 6)
Rocket punch 
-Sent an job offer to 30 people (daily limit is 30)
-9 people took the offer and sent devpool link

**Comment by diamondnegroni** [comment]
Updated (Feb 16)
LInkedin 
-22 applicatns(3 new) , 48 views (3 new)

*Rocket Punch (local recruiting platform)
-173 interested(77 new) , no applied

**Comment by 0x4007** [comment]
> Updated (Feb 16) LInkedin -22 applicatns(3 new) , 48 views (3 new)
> 
> *Rocket Punch (local recruiting platform) -173 interested(77 new) , no applied

Perhaps you can post updates related to the TypeScript recruiting under #3 in order to keep the conversation organized?
