### ISSUE TITLE
Hire two (or more) talented TypeScript developers

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/recruiting#3]
- With the intent to transition them to in-office work.
- Recommended duration: 1 December to 1 February

For

- Bot maintenance
- Dollar UI maintenance.
- More are always welcomed, although we may have them contribute strictly via the DevPool (no/low base pay)

**Comment by 0x4007** [comment]
Any candidates of interest this week? I just realized that the recommended duration is until 1 February so I think we will need to settle up with the current top candidates (they seem solid!) 

Perhaps its worth focusing on the business development / investor relations talent? 

rfc (request for comment) @diamondnegroni

**Comment by 0x4007** [comment]
I made a custom label for 1 Month. I'm not sure if that will work. I suppose it would have been optimal to break down the campaign into smaller (per week) tasks 

Examples: 
1. post on RocketTalent (or whatever its called.)
2. post on linkedin
3. interviews
 
This detailed approach has several benefits:

1. work audibility
2. higher compensation in rewards

Although I understand this may have had a lot of friction because the payouts are only starting to work just this week. I appreciate your patience and I hope that you continue to try and become familiar with the system in order to increase your rewards compensation (while allowing us more opportunities to improve the system for non code deliverables!)

---

Lastly it is important to regularly post updates on the issues that you are assigned to or the bot will unassign you. We used to have a follow up feature but that hasn't been migrated over yet.

**Comment by 0x4007** [comment]
lol it worked thats crazy. In the future, lets not use the 1 month label. We should break this down into smaller tasks [as I mentioned above](https://github.com/ubiquity/recruiting/issues/3#issuecomment-1946123760). 

You should create those proposals for your upcoming weeks of work, and I can set prices for them on whenever I get chances to review your proposals. This will allow us to 1. stay in sync 2. share information transparently with the organization (very useful when you have team members working directly with you) and 3. receive rewards.

**Comment by diamondnegroni** [comment]
I'll be having a coffee chat with a candidate found on GitHub, [thyoondev](https://github.com/thyoondev), on February 19th, marking the conclusion of my current candidate evaluations. I will start focusing on the business development / investor relations position.

**Market Feedback Update (As of February 19):**

**LinkedIn:**
- Job Post Engagement: Received a total of 22 applications (3 new since last update) and 48 profile views (3 new).

**Rocket Punch (Local Recruiting Platform):**
- Job Post Engagement: 223 individuals showed interest (50 new since last update), yet none have applied.
- Personal Follow-Up: Reached out to 40 members directly.

**Coding Communities on Kakao and Naver:**
- Job Posting Traction: Made 14 job postings, resulting in two inquiries.
- Informal Engagements: Scheduled one coffee chat with [thyoondev](https://github.com/thyoondev).

**We-connect (Inactive):**
- From over 400 messages sent via the automated system, only 5 responses were received, with none progressing to trying the devpool or moving forward to an interview.

**Comment by 0x4007** [comment]
> I'll be having a coffee chat with a candidate found on GitHub, [thyoondev](https://github.com/thyoondev), on February 19th, marking the conclusion of my current candidate evaluations. I will start focusing on the business development / investor relations position.
> 
> **Market Feedback Update (As of February 19):**
> 
> **LinkedIn:**
> 
> * Job Post Engagement: Received a total of 22 applications (3 new since last update) and 48 profile views (3 new).
> 
> **Rocket Punch (Local Recruiting Platform):**
> 
> * Job Post Engagement: 223 individuals showed interest (50 new since last update), yet none have applied.
> * Personal Follow-Up: Reached out to 40 members directly.
> 
> **Coding Communities on Kakao and Naver:**
> 
> * Job Posting Traction: Made 14 job postings, resulting in two inquiries.
> * Informal Engagements: Scheduled one coffee chat with [thyoondev](https://github.com/thyoondev).

They can certainly contribute in the public DevPool. If they prove themself then we can extend an offer. I'm skeptical because from the surface they seem a bit green.

> **We-connect (Inactive):**
> 
> * From over 400 messages sent via the automated system, only 5 responses were received, with none progressing to trying the devpool or moving forward to an interview.

Automation shows its power when you run massive numbers (think like 10'000+) but the response rate is lower than I expect. Perhaps you can share what you sent so I can help you out.

**Comment by diamondnegroni** [comment]
https://docs.google.com/document/d/1m_JZpr3h0Do2rxhG7sWnsvu6R4obNT__8sRUQ2oOWSg/edit
I was using the 4 steps follow-up meesages that you created.  I think the sample size is small given there are lots of restrctions such as georaphics, years of experience, specific development languanges and Bilangual (Korea and English)

**Comment by 0x4007** [comment]
> https://docs.google.com/document/d/1m_JZpr3h0Do2rxhG7sWnsvu6R4obNT__8sRUQ2oOWSg/edit
> 
> and Bilangual (Korea and English)  

We can do English only if that helps!

**Comment by diamondnegroni** [comment]
The sample size didn't change much by changing bi-lingual to english only in korea.

**Comment by 0x4007** [comment]
We're just about out of time on the project. I presume that you were unable to find another viable TypeScript candidate in Seoul?

**Comment by diamondnegroni** [comment]
Still processing canddiates through devpool

**Comment by 0x4007** [comment]
As mentioned in the performance review. I think that this was technically accomplished but I think that one of the candidates is better suited for research. As such, I'll still need to continue active recruiting efforts for more TypeScript developers.
