### ISSUE TITLE
Hire business development/fundraising team

### ISSUE THREAD

**Issue by 0x4007** [ubiquity/recruiting#4]
- Recommended duration: 15 January to 1 March 

For

- Lead generation
- Sales/investor relations

**Comment by 0x4007** [comment]
@diamondnegroni I'm guessing we're not going to have any luck on this in time for 1 March?

**Comment by diamondnegroni** [comment]
I will post the progress on two positions here.

**Comment by 0x4007** [comment]
To clarify I want to hire them for fundraising (investor relations) but then transition them into business development roles post raise.

**Comment by diamondnegroni** [comment]
As a part of interview process, Would you like to have candidates to pitch Ubiquity DAO to you ?

**Comment by 0x4007** [comment]
> As a part of interview process, Would you like to have candidates to pitch Ubiquity DAO to you ?

I don't have a lot of experience hiring business developers. We should figure out a process that is low touch so that we can screen through most of the applicants. Then we can focus our time and energy on the top picks and bring them out on the town to see how they carry themselves. 

I also think we should consider going through our existing network.

I will have more ideas once we start the process.

Lets go with your recommendation to start.
