### ISSUE TITLE
# Standard Operating Procedure (SOP) for Recruitment at Ubiquity DAO

### ISSUE THREAD

**Issue by diamondnegroni** [ubiquity/recruiting#5]
## Purpose

This document outlines the procedure for effective recruitment at Ubiquity DAO, aimed at attracting and hiring candidates who align with the organization's vision and culture in the blockchain and DeFi sectors.

## Scope

This SOP is applicable for the recruitment of various roles within Ubiquity DAO.

## Table of Contents

1. [Pre-Recruitment Preparation](#pre-recruitment-preparation)
2. [Job Posting and Promotion](#job-posting-and-promotion)
3. [Candidate Sourcing: Utilizing WeConnect for LinkedIn Outreach](#candidate-sourcing-utilizing-weconnect-for-linkedin-outreach)
4. [Screening Process: Candidate-Initiated Task Selection in Ubiquity DevPool](#screening-process-candidate-initiated-task-selection-in-ubiquity-devpool)
5. [Interview Process](#interview-process)
6. [Reference and Background Checks](#reference-and-background-checks)
7. [Job Offer and Negotiation](#job-offer-and-negotiation)
8. [Onboarding](#onboarding)
9. [Conclusion](#conclusion)

---

<a name="pre-recruitment-preparation"></a>
## 1. Pre-Recruitment Preparation

- **Developing Job Descriptions**: Create detailed job descriptions for each position.
- **Identifying Recruitment Platforms**: Select suitable global and local platforms for job advertisements.
- **Engaging with Crypto-Related Communities**: Participate in relevant online communities for sourcing candidates.
- **Identifying Local Crypto Events**: Use local events for networking and promoting Ubiquity DAO's positions.

---

<a name="job-posting-and-promotion"></a>
## 2. Job Posting and Promotion

- **Objective**: Achieve optimal visibility of job openings.
- **Action**: Distribute job postings across selected platforms and leverage Ubiquity DAO’s network for wider reach.
- **Boosting Visibility**: Use paid services for enhanced visibility if needed, and update potential candidates with recent DAO activities.

---

<a name="candidate-sourcing-utilizing-weconnect-for-linkedin-outreach"></a>
## 3. Candidate Sourcing: Utilizing WeConnect for LinkedIn Outreach

- **Objective**: Streamline the outreach process for potential candidates.
- **Actions**:
    - Sign up and integrate LinkedIn with WeConnect.
    - Create targeted search filters on LinkedIn.
    - Initiate automated messaging campaigns.

---

<a name="screening-process-candidate-initiated-task-selection-in-ubiquity-devpool"></a>
## 4. Screening Process: Candidate-Initiated Task Selection in Ubiquity DevPool

- **Objective**: Assess candidates' technical abilities and fit for DAO-centric work.
- **Actions**:
    - Direct candidates to select tasks from the Ubiquity DevPool.
    - Monitor their engagement and technical problem-solving skills.

---

<a name="interview-process"></a>
## 5. Interview Process

- **Objective**: Conduct in-depth candidate evaluations.
- **Actions**: Implement structured interviews, including technical assessments and discussions about candidates' experiences and aspirations.

---

<a name="reference-and-background-checks"></a>
## 6. Reference and Background Checks

- **Objective**: Verify the candidates' professional history and suitability.
- **Action**: Conduct comprehensive reference and background checks.

---

<a name="job-offer-and-negotiation"></a>
## 7. Job Offer and Negotiation

- **Objective**: Secure the best candidate with an appealing job offer.
- **Action**: Prepare and present a competitive offer, negotiating terms as needed.

---

<a name="onboarding"></a>
## 8. Onboarding

- **Objective**: Integrate new hires effectively into Ubiquity DAO.
- **Action**: Provide comprehensive onboarding, including orientation and training.

---

<a name="conclusion"></a>
## 9. Conclusion

This SOP is designed to ensure a streamlined and effective recruitment process, contributing significantly to Ubiquity DAO's success in the blockchain and DeFi sectors.

---

This Markdown document is ready to be uploaded to GitHub or any other platform that supports Markdown formatting, providing a clear and structured guide for Ubiquity DAO's recruitment activities.

**Comment by 0x4007** [comment]
This is a good start but there's several adjustments that are required:

1. this should be delivered in a pull request so that I can easily offer line-by-line feedback, as well as for us to be able to save it in this repository for later use. 
2. this should include all of the details we covered, for example, negotiating points for why a lower base pay could be more attractive for candidates; as well as specifics around which job listing websites to post to. 

The purpose of this standard operating procedure documentation is so that we can hire a dedicated team member for recruiting and give them this document in order for them to do their job effectively. This document should incorporate all of your learnings since starting in December.
